### ISSUE TITLE
Staging build

### ISSUE THREAD

**Issue by vzrenggamani** [DiscordBotsDev/Rendang#5]
## Separate Bot with different staging arena

Summary :
- Heroku hosting used for Main Bot Release, ( Fixed Code and Cleanup )
- Glitch hosting used for development staging ( testing experimental code and other dirty stuffs )

### Quick Fix

1. Set master branch deployment to heroku hosting
2. While Development branch goes to glitch deployment

#### Advantages

1. Clean release

#### Disadvantages 

1. Too much work todo for deployment man ( of course me :p )

#

## What i have done

- [x] Setting auto deployment to heroku with CI 
- [ ] Setting up glitch-deploy ( my server won't boot up )
- [ ] Setting Local API Key
- [x] Fixing Branch Conflict
- [x] Remaster the repos branch

**Comment by vzrenggamani** [comment]
Any idea about Glitch auto deploy ?

**Comment by Hazmi35** [comment]
idk

**Comment by Hazmi35** [comment]
Hello?

**Comment by SharifPoetra** [comment]
I'm Removed :(

**Comment by Hazmi35** [comment]
Because of In-Activity, this issue closed.
